# Generated by Django 3.2 on 2021-10-07 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdmSchedule', '0002_alter_schedule_options'),
        ('gymTeachers', '0001_initial'),
        ('gymServices', '0002_alter_service_options'),
        ('gymClients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(db_column='Capacity')),
                ('dayofweek', models.IntegerField(db_column='dayOfWeek')),
                ('dayofmonth', models.IntegerField(db_column='dayOfMonth')),
                ('startime', models.TimeField(db_column='StarTime')),
                ('endtime', models.TimeField(db_column='EndTime')),
                ('client', models.ManyToManyField(to='gymClients.Client')),
                ('schedule', models.ForeignKey(db_column='Schedule_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='AdmSchedule.schedule')),
                ('service', models.ForeignKey(db_column='Service_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='gymServices.service')),
                ('teacher', models.ForeignKey(db_column='Teacher_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='gymTeachers.teacher')),
            ],
            options={
                'db_table': 'Activity',
                'managed': True,
            },
        ),
    ]
