# Generated by Django 3.2 on 2021-10-07 23:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymServices', '0003_alter_service_options'),
        ('gymTeachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='services',
            field=models.ManyToManyField(to='gymServices.Service'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teachercategory',
            field=models.ForeignKey(db_column='TeacherCategory_ID', on_delete=django.db.models.deletion.CASCADE, to='gymTeachers.teachercategory'),
            preserve_default=False,
        ),
    ]
