# Generated by Django 3.2 on 2021-10-07 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdmSchedule', '0001_initial'),
        ('gymSettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='gym',
            field=models.ForeignKey(db_column='Gym_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='gymSettings.gym'),
        ),
        migrations.AddField(
            model_name='room',
            name='schedule',
            field=models.ForeignKey(db_column='Schedule_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='AdmSchedule.schedule'),
        ),
    ]
