# Generated by Django 3.2 on 2021-10-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdmSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': False},
        ),
    ]
