# Generated by Django 3.2 on 2021-10-07 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdmSchedule', '0002_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'managed': True},
        ),
    ]
