# Generated by Django 3.2 on 2021-10-07 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False},
        ),
    ]
